version: "3.0"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=atria
      - POSTGRES_USER=senior
      - POSTGRES_PASSWORD=Living!
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    ports:
      - "5432:5432"
    networks:
      - atria-network

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - atria-network

  proxy:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-proxy
    image: atria-proxy
    environment:
      APP_NAME: 'proxy-service in docker'
      GRPC_PRODUCT_HOST: 'items'
      GRPC_PRODUCT_PORT: 5001
      GRPC_COUNTER_HOST: 'waitstaff'
      GRPC_COUNTER_PORT: 5002
    ports:
      - 5000:5000
    depends_on:
      - items
    networks:
      - atria-network

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-web
    image: atria-web
    environment:
      REVERSE_PROXY_URL: http://localhost:5000
      WEB_PORT: 8888
    ports:
      - 8888:8888
    depends_on:
      - proxy
    networks:
      - atria-network

  items:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-items
    image: atria-items
    environment:
      APP_NAME: 'items-service in docker'
    ports:
      - 5001:5001
    networks:
      - atria-network

  waitstaff:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-waitstaff
    image: atria-waitstaff
    environment:
      APP_NAME: 'waitstaff-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://senior:Living!@atria:5432/postgres
      PG_DSN_URL: host=postgres user=senior password=Living! dbname=atria sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      ITEMS_CLIENT_URL: items:5001
    ports:
      - 5002:5002
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - atria-network

  cook:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-cook
    image: atria-cook
    environment:
      APP_NAME: 'cook-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://senior:Living!@atria:5432/postgres
      PG_DSN_URL: host=postgres user=senior password=Living! dbname=atria sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - atria-network

  chef:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-chef
    image: atria-hef
    environment:
      APP_NAME: 'chef-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://senior:Living!@atria:5432/postgres
      PG_DSN_URL: host=postgres user=senior password=Living! dbname=atria sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - atria-network

networks:
  atria-network:
