version: "3.0"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=atria
      - POSTGRES_USER=senior
      - POSTGRES_PASSWORD=Living!
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    ports:
      - "5432:5432"
    networks:
      - atria-network

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - atria-network

  proxy:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-proxy
    image: atria-proxy
    environment:
      APP_NAME: 'proxy-service in docker'
      GRPC_PRODUCT_HOST: 'items'
      GRPC_PRODUCT_PORT: 5001
      GRPC_COUNTER_HOST: 'waitstaff'
      GRPC_COUNTER_PORT: 5002
    ports:
      - 5000:5000
    depends_on:
      - items
    networks:
      - atria-network

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-web
    image: atria-web
    environment:
      REVERSE_PROXY_URL: http://localhost:5000
      WEB_PORT: 8888
    ports:
      - 8888:8888
    depends_on:
      - proxy
    networks:
      - atria-network

  items:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-items
    image: atria-items
    environment:
      APP_NAME: 'items-service in docker'
    ports:
      - 5001:5001
    networks:
      - atria-network

networks:
  atria-network:
