// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/ntv97/atriaseniorliving/cmd/items/config"
	"github.com/ntv97/atriaseniorliving/internal/items/app/router"
	"github.com/ntv97/atriaseniorliving/internal/items/infras/repo"
	"github.com/ntv97/atriaseniorliving/internal/items/usecases/items"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, grpcServer *grpc.Server) (*App, error) {
	itemRepo := repo.NewOrderRepo()
	useCase := items.NewService(itemRepo)
	itemServiceServer := router.NewItemGRPCServer(grpcServer, useCase)
	app := New(cfg, useCase, itemServiceServer)
	return app, nil
}
