// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type OrderLineItem struct {
	ID             uuid.UUID     `json:"id"`
	ItemType       int32         `json:"item_type"`
	ItemName       string        `json:"item_name"`
	OrderName      string        `json:"order_name"`
	ItemStatus     int32         `json:"item_status"`
	OrderType      string         `json:"order_type"`
	OrderID        uuid.NullUUID `json:"order_id"`
	Created        time.Time     `json:"created"`
	Updated        sql.NullTime  `json:"updated"`
}

type OrderOrder struct {
	ID              uuid.UUID    `json:"id"`
	OrderTable      int32        `json:"order_table"`
	OrderName	string	     `json:"order_name"`
	OrderStatus     int32        `json:"order_status"`
	Updated         sql.NullTime `json:"updated"`
}
