app:
  name: 'reverse-proxy'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5000

grpc:
  items_host: '0.0.0.0'
  items_port: 5001
  counter_host: '0.0.0.0'
  counter_port: 5002

logger:
  log_level: 'debug'
  rollbar_env: 'reverse-proxy'
